name: Build LaTeX and Update Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install LaTeX (minimal version)
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra
          sudo apt-get install -y texlive-fonts-recommended texlive-fonts-extra
          sudo apt-get install -y latexmk
      
      - name: Build PDF
        working-directory: ./build
        run: |
          make -B stat205.pdf
          ls -la  # Verify PDF was created
      
      # Verify PDF exists before release
      - name: Check PDF exists
        run: |
          if [ ! -f build/stat205.pdf ]; then
            echo "::error::PDF was not generated!"
            exit 1
          fi
      
      # Create/update release
      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/stat205.pdf
          tag_name: "latest"
          name: "Latest Book Version"
          body: "Automatically generated - ${{ github.sha }}"
          replace_assets: true
          draft: false
