name: PDF Release Only

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # Install dependencies
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra \
              texlive-fonts-recommended texlive-fonts-extra \
              latexmk texlive-bibtex-extra biber

      # Build PDF
      - name: Build PDF
        working-directory: ./build
        run: |
          make -B stat205.pdf
          [ -f stat205.pdf ] || { echo "::error::PDF not generated!"; exit 1; }

      # Safely delete previous release (if exists)
      - name: Clean previous release
        run: |
          # Delete release (ignores errors)
          gh release delete latest --yes || true
          # Delete local tag (ignores errors)
          git tag -d latest || true
          # Delete remote tag (ignores errors)
          git push origin :refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Get current date
      - name: Get release date
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Create new release with only PDF
      - name: Create PDF release
        uses: softprops/action-gh-release@v1
        with:
          files: build/stat205.pdf
          tag_name: latest
          release_name: "STAT205 - ${{ env.RELEASE_DATE }}"
          body: |
            Latest PDF version (${{ env.RELEASE_DATE }})
            Commit: ${{ github.sha }}
          draft: false